name: tests-auth
on:
  pull_request:
    paths:
      - 'app/auth/**'
  
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd app/auth && npm install && docker build -t lahcenedergham/auth . && docker push lahcenedergham/auth
      - name: Login to GitHub Container Registry
      - uses: docker/login-action@v1
      - with:
        - registry: ghcr.io
        - username: LahceneDer
        - password: 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
