apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - ../k8s/*
build:
  local:
    push: true
  artifacts:
    - image: lahcenedergham/auth
      context: ../app/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: lahcenedergham/client
      context: ../client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
<<<<<<< HEAD
          - src: '**/*.ts'
            dest: .
    - image: lahcenedergham/tickets
      context: ../tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
=======
          - src: '**/*.js'
>>>>>>> ed2ce2005ebd605273fb0cb06b2a912ba9238cd8
            dest: .